name: DarkXArmy

on:
  workflow_dispatch:

jobs:
  build:
    name: Start Building...
    runs-on: windows-latest
    timeout-minutes: 120

    steps:
    - name: Downloading & Installing Essentials
      shell: pwsh
      run: |
        Invoke-WebRequest -Uri "https://gitlab.com/raposabrty/pcrdp/-/raw/main/Downloads.bat" -OutFile "Downloads.bat"
        cmd /c Downloads.bat

    - name: Verify Downloads.bat Execution
      run: |
        if exist Downloads.bat (echo "Downloads.bat executed successfully") else (exit 1)

    - name: Show Website
      shell: cmd
      run: show.bat

    - name: Verify show.bat Execution
      run: |
        if exist show.bat (echo "show.bat executed successfully") else (exit 1)

    - name: Time Counter
      shell: cmd
      run: loop.bat

    - name: Verify loop.bat Execution
      run: |
        if exist loop.bat (echo "loop.bat executed successfully") else (exit 1)
